In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/patel/.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/patel/.local/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/patel/.local/lib/python3.10/site-packages (from pandas) (2025.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
buyrent=pd.read_csv("all_listings_raw.csv")

buyrent.head()

,source,listing_id,title,location,property_type,bedrooms,bathrooms,size_sqft,price_kes,amenities,listing_url,scrape_date
0,BuyRentKenya,89a2c0cd86,Property,Nairobi,Unknown,NaN,NaN,NaN,25300000,NaN,NaN,2026-02-19
1,BuyRentKenya,354347e742,Property,Nairobi,Unknown,NaN,NaN,NaN,13700000,NaN,NaN,2026-02-19
2,BuyRentKenya,7bdc279289,Property,Nairobi,Unknown,NaN,NaN,NaN,6100000,NaN,NaN,2026-02-19
3,BuyRentKenya,9adf7c7f07,Property,Nairobi,Unknown,NaN,NaN,NaN,10300000,NaN,NaN,2026-02-19
4,BuyRentKenya,bc973fca3f,Property,Nairobi,Unknown,NaN,NaN,NaN,16700000,NaN,NaN,2026-02-19

In [4]:
buyrent.isnull().sum()

source             0
listing_id         0
title              0
location           0
property_type      0
bedrooms         251
bathrooms        251
size_sqft        251
price_kes          0
amenities        251
listing_url       12
scrape_date        0
dtype: int64

In [7]:
dfrentpro=pd.read_csv("listings_20260219_103449.csv")

In [8]:
dfrentpro.head()

,source,listing_id,title,location,property_type,bedrooms,bathrooms,size_sqft,price_kes,amenities,listing_url,scrape_date
0,BuyRentKenya,0a2dad59e9,Property,Nairobi,Unknown,NaN,NaN,NaN,17500000,NaN,NaN,2026-02-19
1,BuyRentKenya,0a2dad59e9,Property,Nairobi,Unknown,NaN,NaN,NaN,17500000,NaN,NaN,2026-02-19
2,BuyRentKenya,b635201147,Property,Nairobi,Unknown,NaN,NaN,NaN,5800000,NaN,NaN,2026-02-19
3,BuyRentKenya,b635201147,Property,Nairobi,Unknown,NaN,NaN,NaN,5800000,NaN,NaN,2026-02-19
4,BuyRentKenya,23dc7b9655,Property,Nairobi,Unknown,NaN,NaN,NaN,6000000,NaN,NaN,2026-02-19